# This is a basic workflow to help you get started with Actions

name: ubuntu
on: [push, pull_request]
jobs:
  image:
    name: ${{ matrix.arch_name }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        arch_name: [android-arm, android-arm64, android-x86, android-x86_64, web-wasm, linux-arm64, linux-arm64-musl, linux-armv5, linux-armv5-musl, linux-armv6, linux-armv6-musl, linux-armv7, linux-armv7a, linux-armv7l-musl, linux-s390x, linux-x64, linux-x86, manylinux1-x64, manylinux1-x86, manylinux2010-x64, manylinux2010-x86, manylinux2014-x64, manylinux2014-x86, manylinux2014-aarch64, windows-static-x64, windows-static-x64-posix, windows-static-x86, windows-shared-x64, windows-shared-x64-posix, windows-shared-x86]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v1
          
